import '../../../../services/permission_service.dart';
import 'dart:convert'; import 'dart:io'; import 'package:flutter/material.dart'; import 'package:flutter/services.dart'; import 'package:flutter_riverpod/flutter_riverpod.dart'; import 'package:go_router/go_router.dart'; import 'package:image_picker/image_picker.dart'; import 'package:flutter_image_compress/flutter_image_compress.dart'; import 'package:path_provider/path_provider.dart'; import '../providers/auth_provider.dart'; import '../../../../services/api_service.dart';
class RegisterScreen extends ConsumerStatefulWidget { const RegisterScreen({super.key}); @override ConsumerState<RegisterScreen> createState() => _RegisterScreenState(); }
class _RegisterScreenState extends ConsumerState<RegisterScreen> { final _form = GlobalKey<FormState>(); final _phone = TextEditingController(), _name = TextEditingController(), _job = TextEditingController(), _addr = TextEditingController(); File? _img; String? _b64; bool _checking=false, _exists=false, _loading=false; String? _msg; static const List<String> _jobs = ['كهربائي','سباك','مهندس','مقاول','معلم ديكور','تاجر','أخرى'];
  @override void dispose() { _phone.dispose(); _name.dispose(); _job.dispose(); _addr.dispose(); super.dispose(); }
  String? _validatePhone(String? v) { if(v==null||v.isEmpty) return 'مطلوب'; if(!v.startsWith('7')) return 'يبدأ بـ7'; if(v.length!=9) return '9 أرقام'; if(_exists) return 'الرقم مسجل'; return null; }
  Future<void> _check() async { final p = _phone.text.trim(); if(p.length!=9||!p.startsWith('7')) { setState((){_exists=false;_msg=null;}); return; } setState(()=>_checking=true); final api = ref.read(apiServiceProvider); final e = await api.checkPhoneExists(p) || await api.checkPendingPhoneExists(p); setState((){_exists=e; _msg=e?'الرقم مسجل':null; _checking=false;}); }
  Future<void> _pick() async { final p = await ImagePicker().pickImage(source: ImageSource.gallery); if(p!=null) { final dir = await getTemporaryDirectory(); final target = '${dir.path}/compressed.jpg'; final compressed = await FlutterImageCompress.compressAndGetFile(p.path, target, quality:75, minWidth:800); if(compressed!=null) { final b = await compressed.readAsBytes(); setState((){_img=File(compressed.path); _b64=base64Encode(b);}); } } }
  Future<void> _submit() async { if(!_form.currentState!.validate()||_exists) return; setState(()=>_loading=true); await ref.read(authProvider.notifier).register(phone: _phone.text.trim(), fullName: _name.text.trim(), occupation: _job.text.trim(), address: _addr.text.trim(), imageBase64: _b64); if(mounted) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('تم الإرسال'))); context.pop(); } setState(()=>_loading=false); }
  @override Widget build(BuildContext context) { return Directionality(textDirection: TextDirection.rtl, child: Scaffold(appBar: AppBar(title: const Text('إنشاء حساب')), body: SingleChildScrollView(padding: const EdgeInsets.all(24), child: Form(key: _form, child: Column(children: [ GestureDetector(onTap: _pick, child: CircleAvatar(radius:60, backgroundColor: Colors.grey.shade200, backgroundImage: _img!=null?FileImage(_img!):null, child: _img==null? const Icon(Icons.add_a_photo, size:40):null)), const SizedBox(height:24), TextFormField(controller: _phone, keyboardType: TextInputType.phone, inputFormatters: [FilteringTextInputFormatter.digitsOnly, LengthLimitingTextInputFormatter(9)], decoration: const InputDecoration(labelText:'رقم الموبايل', prefixText:'7 ', border: OutlineInputBorder()), validator: _validatePhone, onChanged: (_)=>_check()), if(_checking) const CircularProgressIndicator(), if(_msg!=null) Text(_msg!, style: const TextStyle(color:Colors.red)), const SizedBox(height:16), TextFormField(controller: _name, decoration: const InputDecoration(labelText:'الاسم الكامل', border: OutlineInputBorder()), validator: (v)=>v==null||v.isEmpty?'مطلوب':null), const SizedBox(height:16), Autocomplete<String>(optionsBuilder: (v)=>v.text.isEmpty?[]:_jobs.where((j)=>j.contains(v.text)).toList(), onSelected: (v)=>_job.text=v, fieldViewBuilder: (c,ctrl,f,_)=>TextFormField(controller:ctrl, focusNode:f, decoration: const InputDecoration(labelText:'المهنة', border: OutlineInputBorder()), validator: (v)=>v==null||v.isEmpty?'مطلوب':null)), const SizedBox(height:16), TextFormField(controller: _addr, decoration: const InputDecoration(labelText:'العنوان (اختياري)', border: OutlineInputBorder())), const SizedBox(height:32), ElevatedButton(onPressed: _loading?null:_submit, style: ElevatedButton.styleFrom(minimumSize: const Size(double.infinity,50), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12))), child: _loading? const CircularProgressIndicator(): const Text('إنشاء حساب', style: TextStyle(fontSize:18))), TextButton(onPressed: ()=>context.pop(), child: const Text('لديك حساب؟ تسجيل الدخول')) ]))))); } }
