import 'package:flutter_riverpod/flutter_riverpod.dart'; import 'package:shared_preferences/shared_preferences.dart'; import 'package:local_auth/local_auth.dart'; import '../../../../models/user_model.dart'; import '../../../../services/api_service.dart';
final authProvider = StateNotifierProvider<AuthNotifier, AuthState>((ref) => AuthNotifier(ref));
class AuthState { final bool isLoading; final String? error; final UserModel? currentUser; final bool isOfflineMode; const AuthState({this.isLoading=false, this.error, this.currentUser, this.isOfflineMode=false}); AuthState copyWith({bool? isLoading, String? error, UserModel? currentUser, bool? isOfflineMode}) => AuthState(isLoading: isLoading??this.isLoading, error: error, currentUser: currentUser??this.currentUser, isOfflineMode: isOfflineMode??this.isOfflineMode); bool get isAuthenticated => currentUser!=null || isOfflineMode; bool get isAdmin => currentUser?.role=='admin'; bool get isDelivery => currentUser?.role=='delivery'; }
class AuthNotifier extends StateNotifier<AuthState> { final Ref ref; final LocalAuthentication _auth = LocalAuthentication(); AuthNotifier(this.ref) : super(const AuthState()) { _initAdmin(); }
  Future<void> _initAdmin() async { final p = await SharedPreferences.getInstance(); if(!p.containsKey('admin_phone')) { await p.setString('admin_phone','770491653'); await p.setString('admin_password','770491653mall'); await p.setString('admin_name','محمود عبيد'); await p.setString('admin_role','admin'); } }
  Future<void> login({required String phone, required String password, required bool offlineMode, required String role, bool rememberMe=false}) async { state = state.copyWith(isLoading:true, error:null); if(offlineMode) { state = state.copyWith(isLoading:false, currentUser: UserModel(id:'local_$phone', phone:phone, fullName:'مستخدم محلي', role:role, createdAt:DateTime.now()), isOfflineMode:true); return; } final p = await SharedPreferences.getInstance(); final aPhone = p.getString('admin_phone')??'770491653'; final aPass = p.getString('admin_password')??'770491653mall'; final aName = p.getString('admin_name')??'محمود عبيد'; if(phone==aPhone && password==aPass) { final u = UserModel(id:'admin', phone:phone, fullName:aName, role:'admin', createdAt:DateTime.now()); state = state.copyWith(isLoading:false, currentUser:u); if(rememberMe) { await p.setString('saved_phone',phone); await p.setString('saved_password',password); } return; } final api = ref.read(apiServiceProvider); final r = await api.loginWithPhone(phone, password); if(r==null) { state = state.copyWith(isLoading:false, error:'بيانات خاطئة'); return; } final u = UserModel.fromJson(r); state = state.copyWith(isLoading:false, currentUser:u); if(rememberMe) { await p.setString('saved_phone',phone); await p.setString('saved_password',password); } }
  Future<void> register({required String phone, required String fullName, required String occupation, required String address, String? imageBase64}) async { state = state.copyWith(isLoading:true); final api = ref.read(apiServiceProvider); final ok = await api.submitRegistrationRequest(phone:phone, fullName:fullName, occupation:occupation, address:address, imageBase64:imageBase64); state = state.copyWith(isLoading:false, error: ok?null:'فشل الإرسال'); }
  Future<void> requestPasswordReset(String phone) async => await ref.read(apiServiceProvider).addPasswordResetRequest(phone);
  Future<bool> enableBiometric(String phone, String password) async { final can = await _auth.canCheckBiometrics; if(!can) return false; final did = await _auth.authenticate(localizedReason: 'تفعيل البصمة'); if(did) { final p = await SharedPreferences.getInstance(); await p.setString('saved_phone',phone); await p.setString('saved_password',password); await p.setBool('biometric_enabled',true); return true; } return false; }
  void logout() async { state = const AuthState(); final p = await SharedPreferences.getInstance(); await p.remove('saved_phone'); await p.remove('saved_password'); await p.setBool('biometric_enabled',false); }
}
