import 'dart:convert'; import 'package:dio/dio.dart'; import 'package:flutter_riverpod/flutter_riverpod.dart'; import '../core/config/config.dart'; import '../models/user_model.dart'; import '../models/product_model.dart';
final apiServiceProvider = Provider<ApiService>((ref) => ApiService());
class ApiService {
  static const String baseUrl = AppConfig.supabaseUrl; static const String anonKey = AppConfig.supabaseAnonKey;
  late final Dio _dio = Dio(BaseOptions(baseUrl: baseUrl, headers: {'apikey': anonKey, 'Authorization': 'Bearer $anonKey'}, connectTimeout: const Duration(seconds: 15)));
  void updateAuthToken(String t) => _dio.options.headers['Authorization'] = 'Bearer $t';
  Future<bool> checkPhoneExists(String phone) async { try { final r = await _dio.get('/rest/v1/users', queryParameters: {'phone':'eq.$phone','select':'phone'}); return (r.data as List).isNotEmpty; } catch(_) { return false; } }
  Future<bool> checkPendingPhoneExists(String phone) async { try { final r = await _dio.get('/rest/v1/pending_users', queryParameters: {'phone':'eq.$phone','select':'phone'}); return (r.data as List).isNotEmpty; } catch(_) { return false; } }
  Future<Map<String,dynamic>?> loginWithPhone(String phone, String password) async { try { final email = '$phone@binobaid.com'; final r = await _dio.post('/auth/v1/token?grant_type=password', data: {'email':email,'password':password}); if(r.statusCode==200) { final data = r.data; updateAuthToken(data['access_token']); final user = await _dio.get('/rest/v1/users', queryParameters: {'phone':'eq.$phone'}); if((user.data as List).isNotEmpty) return {...user.data[0], 'access_token':data['access_token']}; } } catch(_){} return null; }
  Future<bool> submitRegistrationRequest({required String phone, required String fullName, required String occupation, required String address, String? imageBase64}) async { try { await _dio.post('/rest/v1/pending_users', data: {'phone':phone,'full_name':fullName,'occupation':occupation,'address':address,'image_url':imageBase64,'status':'pending','created_at':DateTime.now().toIso8601String()}); return true; } catch(_) { return false; } }
  Future<bool> addPasswordResetRequest(String phone) async { try { await _dio.post('/rest/v1/password_reset_requests', data: {'phone':phone,'status':'pending','created_at':DateTime.now().toIso8601String()}); return true; } catch(_) { return false; } }
  Future<List<Product>> fetchProducts({required int page, required int pageSize, String? search, String? category}) async { try { final params = <String,dynamic>{'select':'*','limit':pageSize,'offset':(page-1)*pageSize,'order':'name.asc'}; if(search!=null && search.isNotEmpty) params['name'] = 'ilike.%$search%'; if(category!=null && category.isNotEmpty) params['category'] = 'eq.$category'; final r = await _dio.get('/rest/v1/products', queryParameters: params); return (r.data as List).map((e)=>Product.fromJson(e)).toList(); } catch(_) { return []; } }
  Future<List<Product>> searchProducts({required String query, int limit=20}) async { try { final r = await _dio.get('/rest/v1/products', queryParameters: {'select':'*','or':'(name.ilike.%$query%,sku.ilike.%$query%)','limit':limit}); return (r.data as List).map((e)=>Product.fromJson(e)).toList(); } catch(_) { return []; } }
  Future<Product?> fetchProductBySku(String sku) async { try { final r = await _dio.get('/rest/v1/products', queryParameters: {'sku':'eq.$sku'}); if((r.data as List).isNotEmpty) return Product.fromJson(r.data[0]); } catch(_){} return null; }
  Future<void> importProductsBatch(List<Map<String,dynamic>> items) async => await _dio.post('/rest/v1/products', data: items);
  Future<Map<String,dynamic>> syncProducts(List<Map<String,String>> meta) async { try { final r = await _dio.post('/api/admin/products/sync', data: {'products':meta}); return r.data; } catch(_) { return {'updated':[],'deleted':[]}; } }
  Future<List<String>> fetchCategories() async { try { final r = await _dio.get('/rest/v1/products', queryParameters: {'select':'category'}); return (r.data as List).map((e)=>e['category'].toString()).toSet().toList(); } catch(_) { return []; } }
  Future<List<Map<String,dynamic>>> getPendingUsers() async { try { final r = await _dio.get('/rest/v1/pending_users', queryParameters: {'status':'eq.pending'}); return List<Map<String,dynamic>>.from(r.data); } catch(_) { return []; } }
  Future<List<Map<String,dynamic>>> getPasswordResetRequests() async { try { final r = await _dio.get('/rest/v1/password_reset_requests', queryParameters: {'status':'eq.pending'}); return List<Map<String,dynamic>>.from(r.data); } catch(_) { return []; } }
  Future<void> updatePendingUserStatus(String id, String status, {String? rejectReason}) async { final d = {'status':status}; if(rejectReason!=null) d['reject_reason']=rejectReason; await _dio.patch('/rest/v1/pending_users?id=eq.$id', data: d); }
  Future<void> createUserAccount({required String phone, required String fullName, required String role, required String password}) async { await _dio.post('/rest/v1/users', data: {'phone':phone,'full_name':fullName,'role':role,'password_hash':password,'is_active':true,'created_at':DateTime.now().toIso8601String()}); }
  Future<void> updatePasswordResetRequest(String id, String status) async => await _dio.patch('/rest/v1/password_reset_requests?id=eq.$id', data: {'status':status});
  Future<void> createInvoice(Map<String,dynamic> data) async => await _dio.post('/rest/v1/invoices', data: data);
  Future<List<String>> getTables() async => ['users','pending_users','products','invoices','invoice_items','templates','template_items','password_reset_requests','fcm_tokens','settings'];
  Future<List<Map<String,dynamic>>> getTableData(String table, {int limit=50}) async { try { final r = await _dio.get('/rest/v1/$table', queryParameters: {'limit':limit}); return List<Map<String,dynamic>>.from(r.data); } catch(_) { return []; } }
  Future<void> insertRecord(String table, Map<String,dynamic> data) async => await _dio.post('/rest/v1/$table', data: data);
  Future<void> updateRecord(String table, Map<String,dynamic> old, Map<String,dynamic> data) async { final id = old['id']; if(id!=null) await _dio.patch('/rest/v1/$table?id=eq.$id', data: data); }
  Future<void> deleteRecord(String table, Map<String,dynamic> rec) async { final id = rec['id']; if(id!=null) await _dio.delete('/rest/v1/$table?id=eq.$id'); }
  Future<Map<String,dynamic>> getSettings() async { try { final r = await _dio.get('/rest/v1/settings'); Map<String,dynamic> s={}; for(var i in r.data) s[i['key']]=i['value']; return s; } catch(_) { return {}; } }
  Future<void> updateSetting(String key, String value) async { try { await _dio.post('/rest/v1/settings', data: {'key':key,'value':value}); } catch(_) { await _dio.patch('/rest/v1/settings?key=eq.$key', data: {'value':value}); } }
  Future<void> updateUserProfile({String? fullName, String? avatarUrl}) async { final d = <String,dynamic>{}; if(fullName!=null) d['full_name']=fullName; if(avatarUrl!=null) d['avatar_url']=avatarUrl; await _dio.patch('/rest/v1/users', data: d); }
  Future<void> changePassword(String newPassword) async => await _dio.post('/auth/v1/user/password', data: {'password':newPassword});
  Future<List<Map<String,dynamic>>> getDeliveryOrders() async { try { final r = await _dio.get('/rest/v1/invoices', queryParameters: {'status':'in.(pending,assigned,picked_up)','order':'created_at.desc'}); return List<Map<String,dynamic>>.from(r.data); } catch(_) { return []; } }
  Future<void> updateOrderStatus(int id, String status) async => await _dio.patch('/rest/v1/invoices?id=eq.$id', data: {'status':status});
  Future<Map<String,dynamic>> getDashboardStats() async { try { final r1 = await _dio.get('/rest/v1/invoices', queryParameters: {'select':'count'}); final r2 = await _dio.get('/rest/v1/invoices', queryParameters: {'select':'sum(total_amount)'}); final r3 = await _dio.get('/rest/v1/invoices', queryParameters: {'select':'count', 'created_at':'gte.${DateTime.now().subtract(Duration(days:1)).toIso8601String()}'}); final r4 = await _dio.get('/rest/v1/products', queryParameters: {'select':'sum(stock_quantity)'}); return { 'newOrders': r1.data[0]['count']??0, 'totalSales': r2.data[0]['sum']??0.0, 'dailyInvoices': r3.data[0]['count']??0, 'availableProducts': r4.data[0]['sum']??0 }; } catch(_) { return {'newOrders':0,'totalSales':0.0,'dailyInvoices':0,'availableProducts':0}; } }
}
